apiVersion: v1
kind: Service
metadata:
  name: {{ include "appsemble.fullname" . }}
  labels:
    {{ include "appsemble.labels" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/name: {{ include "appsemble.name" . }}
